#!/usr/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

list=( $(ls -1 ${HOME}/.66/conf/boot-user) )
for i in ${list[@]};do
    var=$(<${HOME}/.66/conf/boot-user/${i})
    for j in ${var[@]}; do
		export ${j}
    done
done


66-all up

## Try consolekit
if 66-which -q ck-launch-session; then
	cmd="exec ck-launch-session $@"
else
	cmd="exec $@"
fi

## Select the session to start
#${cmd} jwm
#${cmd} openbox-session
#${cmd} startkde

xrandr --output DP1 --off
xrandr --output DP2 --off
xrandr --output DP3 --off
xrandr --output HDMI1 --off
xrandr --output HDMI2 --off
xrandr --output HDMI3 --off
xrandr --output VGA1 --off
xrandr --output VIRTUAL1 --off
#xrandr --output LVDS1 --dpi 125.37
xrandr --output LVDS1 --auto

xsetroot -cursor_name left_ptr

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

exec hsetroot -full ~/Pictures/Wallpaper/Landscape/liliya-shafikova-1.jpg &
exec compton -b --backend glx --blur-method kawase --blur-background --blur-strength 1 &
exec xbanish &
exec dunst &
exec autocutsel &                                                           0
exec autocutsel -selection PRIMARY &                                        0
exec sxhkd ~/.config/sxhkd/bspwm_sxhkdrc &

exec bspwm
